# Generated by Django 5.2.9 on 2026-05-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_payment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payment',
            new_name='payment_subscri_1c7a45_idx',
            old_name='payment_subscri_9d5a0d_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payment_gateway_32ac4e_idx',
            old_name='payment_gateway_57c4f2_idx',
        ),
        migrations.AlterField(
            model_name='payment',
            name='metadata_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
