# Generated by Django 5.2.9 on 2026-05-21 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0006_actividadresoluble_intentoresoluble_and_more'),
        ('cursos', '0004_fix_foreignkey_integrity'),
        ('institucion', '0010_colegio_slug_logo_color_primario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CriterioRubrica',
            fields=[
                ('id_criterio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('peso', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('orden', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Criterio de Rúbrica',
                'verbose_name_plural': 'Criterios de Rúbrica',
                'db_table': 'criterio_rubrica',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='NivelRubrica',
            fields=[
                ('id_nivel', models.AutoField(primary_key=True, serialize=False)),
                ('puntaje', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('orden', models.IntegerField(default=1)),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveles', to='academico.criteriorubrica')),
            ],
            options={
                'verbose_name': 'Nivel de Rúbrica',
                'verbose_name_plural': 'Niveles de Rúbrica',
                'db_table': 'nivel_rubrica',
                'ordering': ['-puntaje', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='ObjetivoAprendizaje',
            fields=[
                ('id_oa', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('nivel', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos_aprendizaje', to='cursos.asignatura')),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos_aprendizaje', to='institucion.colegio')),
            ],
            options={
                'verbose_name': 'Objetivo de Aprendizaje',
                'verbose_name_plural': 'Objetivos de Aprendizaje',
                'db_table': 'objetivo_aprendizaje',
                'ordering': ['codigo'],
                'unique_together': {('colegio', 'asignatura', 'codigo', 'nivel')},
            },
        ),
        migrations.AddField(
            model_name='planificacion',
            name='objetivos_aprendizaje',
            field=models.ManyToManyField(blank=True, db_table='planificacion_oa_link', related_name='planificaciones', to='academico.objetivoaprendizaje'),
        ),
        migrations.CreateModel(
            name='Rubrica',
            fields=[
                ('id_rubrica', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('es_compartida', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubricas', to='cursos.asignatura')),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubricas', to='institucion.colegio')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubricas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rúbrica',
                'verbose_name_plural': 'Rúbricas',
                'db_table': 'rubrica',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='criteriorubrica',
            name='rubrica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios', to='academico.rubrica'),
        ),
        migrations.AddField(
            model_name='planificacion',
            name='rubrica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planificaciones', to='academico.rubrica'),
        ),
    ]
