# Generated by Django 5.2.9 on 2026-05-21 20:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recursodigital_es_plan_lector_and_more'),
        ('institucion', '0010_colegio_slug_logo_color_primario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CasoBullyingConvivencia',
            fields=[
                ('id_caso', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_falta', models.CharField(choices=[('BULLYING', 'Bullying'), ('CIBERBULLYING', 'Ciberbullying'), ('AGRESION_FISICA', 'Agresión Física'), ('AGRESION_VERBAL', 'Agresión Verbal'), ('DISCRIMINACION', 'Discriminación'), ('OTRA_GRAVE', 'Otra Falta Grave')], max_length=20)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_INVESTIGACION', 'En Investigación'), ('MEDIDAS_APLICADAS', 'Medidas Aplicadas'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=20)),
                ('descripcion_hechos', models.TextField()),
                ('medidas_tomadas', models.TextField(blank=True, default='', help_text='Medidas disciplinarias/apoyo aplicadas')),
                ('apoderado_notificado', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos_bullying', to='institucion.colegio')),
                ('estudiante_implicado', models.ForeignKey(limit_choices_to={'role__nombre__in': ['Alumno', 'Estudiante']}, on_delete=django.db.models.deletion.CASCADE, related_name='casos_convivencia_implicado', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='casos_convivencia_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caso de Bullying y Convivencia',
                'verbose_name_plural': 'Casos de Bullying y Convivencia',
                'db_table': 'caso_bullying_convivencia',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['estudiante_implicado', '-fecha_registro'], name='caso_bullyi_estudia_09dd1b_idx'), models.Index(fields=['colegio', '-fecha_registro'], name='caso_bullyi_colegio_151318_idx')],
            },
        ),
        migrations.CreateModel(
            name='CitacionApoderado',
            fields=[
                ('id_citacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_citacion', models.DateTimeField()),
                ('motivo', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ASISTIO', 'Asistió'), ('INASISTENTE', 'Inasistente'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=15)),
                ('observaciones', models.TextField(blank=True, default='', help_text='Notas confidenciales de la citación')),
                ('acuerdos', models.TextField(blank=True, default='', help_text='Acuerdos alcanzados en la reunión')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citaciones_apoderados', to='institucion.colegio')),
                ('estudiante', models.ForeignKey(limit_choices_to={'role__nombre__in': ['Alumno', 'Estudiante']}, on_delete=django.db.models.deletion.CASCADE, related_name='citaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citaciones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Citación de Apoderado',
                'verbose_name_plural': 'Citaciones de Apoderados',
                'db_table': 'citacion_apoderado',
                'ordering': ['-fecha_citacion'],
                'indexes': [models.Index(fields=['estudiante', '-fecha_citacion'], name='citacion_ap_estudia_17ed5b_idx'), models.Index(fields=['colegio', '-fecha_citacion'], name='citacion_ap_colegio_b7d1ea_idx')],
            },
        ),
    ]
